spring:
  security:
   oauth2:
     client:
       registration:
         github:
           client-id: ${githubClientId}
           client-secret: ${githubClientSecret}
         google:
           client-id: ${googleClientId}
           client-secret: ${googleClientSecret}

  jpa:
    hibernate:
      ddl-auto: update